[project]
name = "store"
version = "0.1.0"
description = "A function for performing mathematical calculations."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]==0.115.4",
    "asgi-correlation-id==4.3.4",
    "requests==2.32.3",
    "beamlit==0.0.20rc5",
]
