[project]
name = "store"
version = "0.1.0"
description = "Beamlit langchain agents for providers"
authors = [
    { name = "cploujoux", email = "cploujoux@beamlit.com" },
]
requires-python = ">=3.12,<=3.13"
dependencies = [
    "beamlit>=0.0.42"
]
