[project]
name = "store"
version = "0.1.0"
description = "A function for performing mathematical calculations."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.4",
    "langchain-community>=0.3.3",
    "pygithub>=2.5.0",
    "tiktoken>=0.8.0"
]
