name: Tools

on:
  push:
    branches: ["main"]
    paths:
      - "agent-tools/**"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  find-out-changes:
    runs-on: ubuntu-latest
    outputs:
      dirs: ${{ steps.changed-files.dirs }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          dir_names: true

  build-tool:
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.find-out-changes.outputs.dirs)}}
    needs:
      - find-out-changes
    steps:
      - uses: actions/checkout@v3
      - run: echo ${{ matrix.dir }}
