name: Tools

on:
  push:
    branches: ["main"]
    paths:
      - "agent-tools/**"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  gen-matrix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get changed files
        id: diff
        uses: tj-actions/changed-files@v35
        with:
          files: agent-tools/**
          dir_names: true
          json: true
          json_raw_format: true
      - name: Generate tools matrix
        uses: actions/github-script@v6
        id: generator
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const all_changed_files = ${{ steps.diff.outputs.all_changed_files }}
            const toolSet = new Set(all_changed_files.map(file => file.split("/")[1]))
            const uniqueToolsArray = [...toolSet]
            return { tools: uniqueToolsArray }
    outputs:
      matrix: ${{ steps.generator.outputs.result }}
  build-tool:
    if: ${{ fromJson(needs.gen-matrix.outputs.matrix) }}
    needs: gen-matrix
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.gen-matrix.outputs.matrix) }}
    steps:
      - name: Get short node version
        uses: actions/github-script@v6
        id: logger
        with:
          script: |
            console.log("${{ matrix.tools }}")
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          file: ./agent-tools/Dockerfile
          tags: ghcr.io/${{ github.repository_owner }}/agent-tools/${{ matrix.tools }}:latest
          build-args: |
            TOOL=${{ matrix.tools }}
